oath_key: MONICA_API_KEY
api_url: https://MONICA_API_URL/api
zim_journal_path: /home/MONICA_API_LOCAL_PLAINTEXT_DIR/Zim/Main/Journal
zim_header:
  - "Content-Type: text/x-zim-wiki"
  - "Wiki-Format: zim 0.6"
  - "Creation-Date: "
  - ""
monica_tag:
  start: "<Monica>"
  end: "</Monica>"
titles:
  1: "======"
  2: "====="
  3: "===="
  4: "==="
  5: "=="
monica_title: 3